Args = --no-fallback \
       --enable-native-access=ALL-UNNAMED \
       -H:+AddAllCharsets \
       -H:IncludeResources=org/arig/lucifer/fx/styles.css \
       -H:IncludeResources=org/arig/lucifer/fx/logo.png \
       -H:IncludeResources=org/arig/lucifer/fx/logo_animated.svg \
       -H:IncludeResources=application.yaml
